/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--color-surface-bright)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "alert": "var(--color-alert)",
        "on-surface": "var(--color-on-surface)",
        "pulse": "var(--color-pulse)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "caution": "var(--color-caution)",
        "primary": "var(--color-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "outline": "var(--color-outline)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "outline-variant": "var(--color-outline-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface": "var(--color-surface)",
        "secondary": "var(--color-secondary)",
        "surface-variant": "var(--color-surface-variant)",
        "background": "var(--color-background)",
        "error": "var(--color-error)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary": "var(--color-on-primary)",
        "surface-tint": "var(--color-surface-tint)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container-low": "var(--color-surface-container-low)",
        "growth": "var(--color-growth)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary": "var(--color-on-tertiary)",
        "abyss": "var(--color-abyss)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "ground": "var(--color-ground)",
        "on-secondary": "var(--color-on-secondary)",
        "error-container": "var(--color-error-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "clarity": "var(--color-clarity)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-background": "var(--color-on-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "signal": "var(--color-signal)",
        "on-error": "var(--color-on-error)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "padding-mobile": "24px",
        "container-max": "1000px",
        "unit-sm": "8px",
        "unit-lg": "32px",
        "section-gap": "48px",
        "unit-xs": "4px",
        "gutter": "20px",
        "element-gap": "24px",
        "unit-md": "16px",
        "padding-desktop": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-h1": ["Inter", "sans-serif"],
        "headline-h2": ["Inter", "sans-serif"],
        "headline-h3": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "display-h1-mobile": ["Inter", "sans-serif"],
        "headline-h4": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code": ["Space Mono", "monospace"]
      },
      fontSize: {
        "label-sm": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-h1": ["64px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-h2": ["28px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-h3": ["22px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "caption": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-h1-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-h4": ["19px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "code": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
