/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "secondary-container": "#53456a",
        "on-primary-fixed-variant": "#4230ab",
        "alert": "#E2484A",
        "on-surface": "#e5e2e1",
        "pulse": "#AF9EC9",
        "primary-container": "#8e80fb",
        "primary-fixed-dim": "#c7bfff",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#170065",
        "caution": "#EF9F27",
        "primary": "#c7bfff",
        "surface-container-high": "#2a2a2a",
        "outline": "#928f9f",
        "secondary-fixed-dim": "#d1bfeb",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#86f8c9",
        "surface-container-highest": "#353534",
        "outline-variant": "#474553",
        "on-primary-container": "#24008c",
        "on-secondary-container": "#c6b4e0",
        "surface": "#131313",
        "secondary": "#d1bfeb",
        "surface-variant": "#353534",
        "background": "#131313",
        "error": "#ffb4ab",
        "inverse-on-surface": "#313030",
        "on-primary": "#2b0e95",
        "surface-tint": "#c7bfff",
        "primary-fixed": "#e4dfff",
        "surface-container-low": "#1c1b1b",
        "growth": "#1D9E75",
        "on-secondary-fixed-variant": "#4e4065",
        "on-secondary-fixed": "#211537",
        "on-tertiary-fixed-variant": "#00513a",
        "on-tertiary": "#003827",
        "abyss": "#2C2C2A",
        "on-surface-variant": "#c8c4d5",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed": "#ecdcff",
        "on-tertiary-fixed": "#002115",
        "tertiary": "#68dbae",
        "tertiary-fixed-dim": "#68dbae",
        "ground": "#888780",
        "on-secondary": "#372a4d",
        "error-container": "#93000a",
        "inverse-primary": "#5b4bc4",
        "clarity": "#F3F1FF",
        "on-tertiary-container": "#003121",
        "on-background": "#e5e2e1",
        "tertiary-container": "#26a37a",
        "signal": "#7C6EE8",
        "on-error": "#690005"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "padding-mobile": "24px",
        "container-max": "1000px",
        "unit-sm": "8px",
        "unit-lg": "32px",
        "section-gap": "48px",
        "unit-xs": "4px",
        "gutter": "20px",
        "element-gap": "24px",
        "unit-md": "16px",
        "padding-desktop": "48px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-h1": ["Inter", "sans-serif"],
        "headline-h2": ["Inter", "sans-serif"],
        "headline-h3": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "display-h1-mobile": ["Inter", "sans-serif"],
        "headline-h4": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code": ["Space Mono", "monospace"]
      },
      fontSize: {
        "label-sm": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-h1": ["64px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-h2": ["28px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-h3": ["22px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "caption": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-h1-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-h4": ["19px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "code": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
